version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: nadezh/recipebook_backend
    env_file: ../.env
    volumes:
      - static:/app/backend_static/static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: nadezh/recipebook_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nadezh/recipebook_nginx
    env_file: ../.env
    ports:
      - "7000:80"
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static
      - media:/var/html/media
    depends_on:
      - frontend
